apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: dlp64atuu-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/dlp64atuu-dotnet-basic-gitops